M48
; DRILL file {KiCad 7.0.9} date Wed Nov 29 01:17:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-29T01:17:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.5081Y-2.4331
X2.5081Y-4.2815
X3.473Y-2.4331
X3.473Y-4.2815
T0
M30
